name: nova_aden
description: Sistema de Gestión Operativa para MIPYMES y TCP
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Estado y Arquitectura
  provider: ^6.1.1
  
  # Base de Datos
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  
  # UI y Componentes
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  
  # Compartir archivos
  share_plus: ^10.0.0
  
  # Almacenamiento Seguro
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
